apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapplicationforaks-documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapplicationforaks
  template:
    metadata:
      labels:
        app: sampleapplicationforaks
    spec:
      containers:
      - name: sampleapplicationforaks
        image: acrsample1.azurecr.io/bhanu9505508737/aksasp.net:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: aspapplication
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapplicationforaks
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sampleapplicationforaks
